macro(copydlls MODULELIST)
	foreach(ELEMENT ${MODULELIST})
		get_target_property(LOC_R ${ELEMENT} LOCATION_RELEASE)
		get_target_property(LOC_D ${ELEMENT} LOCATION_DEBUG)
		file(COPY ${LOC_R} DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/Release)
		file(COPY ${LOC_D} DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/Debug)

		get_target_property(DEPENDENCIES_RELEASE ${ELEMENT} IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE)
		foreach(DEPENDENCY ${DEPENDENCIES_RELEASE})
			if(TARGET ${DEPENDENCY})
				get_target_property(LOC_R ${DEPENDENCY} LOCATION_RELEASE)
				file(COPY ${LOC_R} DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/Release)
			endif()
		endforeach()	

		get_target_property(DEPENDENCIES_DEBUG ${ELEMENT} IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG)
		foreach(DEPENDENCY ${DEPENDENCIES_DEBUG})
			if(TARGET ${DEPENDENCY})
				get_target_property(LOC_D ${DEPENDENCY} LOCATION_DEBUG)
				file(COPY ${LOC_D} DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/Debug)
			endif()
		endforeach()	

	endforeach()
endmacro()